# Generated by Django 3.1.4 on 2020-12-06 10:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('men_women_kids', models.CharField(choices=[('M', 'MEN'), ('W', 'WOMEN'), ('G', 'GIRLS'), ('B', 'BOYS'), ('N', 'NEWBORNS')], default='W', max_length=1)),
            ],
            options={
                'verbose_name': 'Категория аксессуаров',
                'verbose_name_plural': 'Категории аксессуаров',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Брэнд',
                'verbose_name_plural': 'Брэнды',
            },
        ),
        migrations.CreateModel(
            name='ClothesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('men_women_kids', models.CharField(choices=[('M', 'MEN'), ('W', 'WOMEN'), ('G', 'GIRLS'), ('B', 'BOYS'), ('N', 'NEWBORNS')], default='W', max_length=1)),
            ],
            options={
                'verbose_name': 'Категория одежды',
                'verbose_name_plural': 'Категории одежды',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название продукта')),
                ('price', models.FloatField(verbose_name='Цена продукта')),
                ('in_stock', models.BooleanField(default=False, verbose_name='Есть в наличии?')),
                ('composition', models.CharField(max_length=300, verbose_name='Состав продукта')),
                ('colour', models.CharField(max_length=100, verbose_name='Цвет продукта')),
                ('description', models.TextField(default='', verbose_name='Описание продукта')),
                ('country', models.CharField(max_length=100, verbose_name='Страна производителя')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('ends_date', models.DateField(default=datetime.date.today, verbose_name='Время окончания скидки')),
                ('is_sport', models.BooleanField(default=False, verbose_name='Это продукт для спорта?')),
                ('city', models.CharField(max_length=100, verbose_name='В каком городе продукт?')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='api.brand', verbose_name='Брэнд продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ShoesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('men_women_kids', models.CharField(choices=[('M', 'MEN'), ('W', 'WOMEN'), ('G', 'GIRLS'), ('B', 'BOYS'), ('N', 'NEWBORNS')], default='W', max_length=1)),
            ],
            options={
                'verbose_name': 'Категория обуви',
                'verbose_name_plural': 'Категории обуви',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Вид спорта',
                'verbose_name_plural': 'Виды спорта',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название магазина')),
                ('address', models.TextField(verbose_name='адрес магазина')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='api.brand', verbose_name='брэнд')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='special_offer_images')),
                ('begins_date', models.DateField(default=datetime.date.today, verbose_name='Дата начало акции')),
                ('ends_date', models.DateField(default=datetime.date.today, verbose_name='Дата окончания акции')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_offers', to='api.brand', verbose_name='брэнд')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Картинка продукта',
                'verbose_name_plural': 'Картинки продукта',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.sport', verbose_name='Вид спорта'),
        ),
        migrations.AddField(
            model_name='product',
            name='stores',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='api.Store', verbose_name='магазины'),
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.product')),
                ('size', models.FloatField(verbose_name='Размер обуви')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.shoescategory', verbose_name='Категория обуви')),
            ],
            options={
                'verbose_name': 'Обувь',
                'verbose_name_plural': 'Обуви',
            },
            bases=('api.product',),
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.product')),
                ('size', models.CharField(max_length=10, verbose_name='Размер одежды')),
                ('size_digit', models.PositiveIntegerField(verbose_name='Размер одежды в цифрах')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.clothescategory', verbose_name='Категория одежды')),
            ],
            options={
                'verbose_name': 'Одежда',
                'verbose_name_plural': 'Одежда',
            },
            bases=('api.product',),
        ),
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.product')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.accessoriescategory', verbose_name='Категория аксессуара')),
            ],
            options={
                'verbose_name_plural': 'Аксессуары',
            },
            bases=('api.product',),
        ),
    ]
